import type { ReviewState, Snapshot } from '@/lib/api'

/**
 * The snapshot the Paper artboard is drawn from. It exists so every state the
 * design covers — a running turn, a stale observation, a pinned queue entry, a
 * run in flight — can be seen without waiting for the pool to be in that shape.
 * Reached with `?example`; the footer says so, and nothing here is ever mixed
 * with live data.
 */
export function exampleSnapshot(now = Date.now()): Snapshot {
  const started = now - 20_000

  return {
    api_version: 1,
    revision: 42,
    generated_at_millis: now,
    collection: { freshness: 'current', errors: [] },
    project_defaults: {
      default_agent: 'codex',
      timeout_seconds: 2700,
      max_followups: 10,
      source: 'local',
      publish: ['fetch'],
      env_profile: null,
      permissions: { codex: 'workspace', cursor: 'unattended', opencode: 'unattended' },
    },
    progress: { total: 8, queued: 1, active: 1, open: 2, closed: 2, failed_like: 2 },
    runs: [
      {
        run_id: 'run-phase-5d',
        name: 'Phase 5d acceptance',
        max_parallel: 2,
        created_at_millis: now - 900_000,
        progress: { total: 3, queued: 0, active: 1, open: 0, closed: 2, failed_like: 0 },
      },
    ],
    tasks: [
      {
        task_id: '0fc80d4600000000000000000000cafe',
        run_id: 'run-phase-5d',
        run_position: 3,
        title: 'Cursor smoke test',
        agent: 'cursor',
        model: 'gpt-5',
        effort: 'high',
        permissions: 'unattended',
        env_profile: 'agents',
        state: 'active',
        blocking_code: null,
        last_outcome: null,
        worker: 'mini-2',
        branch: 'task/0fc80d46',
        turn_count: 1,
        runner: 'live',
        freshness: 'current',
        created_at_millis: started - 5_000,
        updated_at_millis: started,
        active_turn_id: 'turn-0fc80d46',
        close_policy: 'done' as const,
        review_state: 'not_reviewable' as const,
      },
      {
        task_id: 'a1b2c3d400000000000000000000beef',
        run_id: null,
        run_position: null,
        title: 'Fix login redirect loop',
        agent: 'codex',
        model: null,
        effort: null,
        permissions: 'workspace',
        env_profile: null,
        state: 'queued',
        blocking_code: null,
        last_outcome: null,
        worker: 'mini-2',
        branch: null,
        turn_count: 0,
        runner: 'live',
        freshness: 'current',
        created_at_millis: now - 120_000,
        updated_at_millis: now - 120_000,
        active_turn_id: null,
        close_policy: 'done' as const,
        review_state: 'not_reviewable' as const,
      },
      ...(['Flaky billing spec', 'Extract billing client', 'Rewrite the retry policy'] as const).map(
        (title, index) => ({
          task_id: `open${index}`.padEnd(32, '0'),
          run_id: null,
          run_position: null,
          title,
          agent: 'codex',
          model: null,
          effort: null,
          permissions: 'workspace',
          env_profile: null,
          state: 'open' as const,
          blocking_code: null,
          last_outcome: { kind: index === 0 ? 'needs_input' : 'blocked' },
          worker: 'mini-1',
          branch: `task/open${index}`,
          turn_count: 2,
          runner: null,
          freshness: 'current' as const,
          created_at_millis: now - 3_600_000,
          updated_at_millis: now - 600_000,
          active_turn_id: null,
          close_policy: 'done' as const,
          review_state: (index === 0
            ? 'waiting_on_you'
            : 'ready_for_follow_up') as ReviewState,
        }),
      ),
      {
        task_id: 'closed00000000000000000000000001',
        run_id: 'run-phase-5d',
        run_position: 1,
        title: 'Cover the outcome filter parser',
        agent: 'codex',
        model: 'gpt-6-astra',
        effort: 'xhigh',
        permissions: 'workspace',
        env_profile: null,
        state: 'closed',
        blocking_code: null,
        last_outcome: { kind: 'done' },
        worker: 'mini-3',
        branch: 'task/closed001',
        turn_count: 1,
        runner: null,
        freshness: 'current',
        created_at_millis: now - 7_200_000,
        updated_at_millis: now - 5_400_000,
        active_turn_id: null,
        close_policy: 'done' as const,
        review_state: 'closed_after_done' as const,
      },
    ],
    workers: [
      {
        name: 'mini-1',
        health: 'ready',
        freshness: 'current',
        observed_at_millis: now - 2_000,
        hostname: 'mini-1.local',
        agent_facts: {
          collected_at_millis: now - 2_000,
          freshness: 'current',
          agents: [
            { name: 'codex', version: '0.153.2', auth: 'authenticated', auth_by_profile: [] },
            { name: 'cursor', version: '2026.09.02', auth: 'authenticated', auth_by_profile: [] },
            { name: 'claude', version: '2.1.252', auth: 'unauthenticated', auth_by_profile: [] },
          ],
        },
        herdr: { state: 'available', version: '0.9.0', interactive_agents: 0 },
        slot: { state: 'idle', capacity: 1, active_job_id: null },
        capabilities: ['darwin-arm64'],
        missing_capabilities: [],
        system: {
          free_disk_bytes: Math.round(160.7 * 1024 ** 3),
          total_disk_bytes: 245 * 1024 ** 3,
          memory_pressure: 'warn',
          swap_used_bytes: 0,
          cpu_busy_percent: 11,
        },
        error: null,
        active_task: null,
      },
      {
        name: 'mini-2',
        health: 'busy',
        freshness: 'current',
        observed_at_millis: started,
        hostname: 'mini-2.local',
        agent_facts: {
          collected_at_millis: now - 3_000,
          freshness: 'current',
          agents: [
            { name: 'cursor', version: '2026.09.02', auth: 'authenticated', auth_by_profile: [] },
          ],
        },
        herdr: { state: 'available', version: '0.9.0', interactive_agents: 2 },
        slot: { state: 'busy', capacity: 1, active_job_id: 'turn-0fc80d46' },
        capabilities: ['darwin-arm64'],
        missing_capabilities: [],
        system: {
          free_disk_bytes: Math.round(152.2 * 1024 ** 3),
          total_disk_bytes: 245 * 1024 ** 3,
          memory_pressure: 'warn',
          swap_used_bytes: 0,
          cpu_busy_percent: 38.4,
        },
        error: null,
        active_task: {
          task_id: '0fc80d4600000000000000000000cafe',
          title: 'Cursor smoke test',
          agent: 'cursor',
          model: 'gpt-5',
          effort: 'high',
          turn_number: 1,
        },
      },
      {
        name: 'mini-3',
        health: 'ready',
        freshness: 'stale',
        observed_at_millis: now - 23 * 60_000,
        hostname: 'mini-3.local',
        agent_facts: {
          collected_at_millis: now - 23 * 60_000,
          freshness: 'stale',
          agents: [
            { name: 'codex', version: '0.153.2', auth: 'authenticated', auth_by_profile: [] },
          ],
        },
        herdr: { state: 'no_socket', version: '0.9.0' },
        slot: { state: 'idle', capacity: 1, active_job_id: null },
        capabilities: ['darwin-arm64'],
        missing_capabilities: [],
        system: {
          free_disk_bytes: Math.round(59.3 * 1024 ** 3),
          total_disk_bytes: 245 * 1024 ** 3,
          memory_pressure: 'warn',
          swap_used_bytes: 0,
          cpu_busy_percent: 6.3,
        },
        error: null,
        active_task: null,
      },
    ],
    queue: [
      {
        position: 1,
        job_id: 'job-queued-1',
        entry_kind: 'batch',
        task_id: 'a1b2c3d400000000000000000000beef',
        turn_id: null,
        run_id: null,
        run_max_parallel: null,
        pinned_worker: null,
        project_id: 'project-mac-worker',
        worktree_id: 'worktree-main',
        project_label: 'mac-worker',
        command_summary: { mode: 'agent', arg_count: 4 },
        created_at_millis: now - 22 * 60_000,
        requirements: ['agent:codex', 'darwin-arm64'],
        blocking_code: 'NO_COMPATIBLE_IDLE_WORKER',
      },
      {
        position: 2,
        job_id: 'job-queued-2',
        entry_kind: 'task_turn',
        task_id: 'open0'.padEnd(32, '0'),
        turn_id: 'turn-open0-3',
        run_id: null,
        run_max_parallel: null,
        pinned_worker: 'mini-1',
        project_id: 'project-mac-worker',
        worktree_id: 'worktree-main',
        project_label: 'mac-worker',
        command_summary: { mode: 'agent', arg_count: 2 },
        created_at_millis: now - 6 * 60_000,
        requirements: ['agent:codex'],
        blocking_code: 'PINNED_WORKER_BUSY',
      },
      {
        position: 3,
        job_id: 'job-queued-3',
        entry_kind: 'batch',
        task_id: null,
        turn_id: null,
        run_id: 'run-phase-5d',
        run_max_parallel: 2,
        pinned_worker: null,
        project_id: 'project-mac-worker',
        worktree_id: 'worktree-main',
        project_label: 'Second opinion on the anchor plan',
        command_summary: { mode: 'agent', arg_count: 3 },
        created_at_millis: now - 3 * 60_000,
        requirements: ['agent:opencode'],
        blocking_code: 'RUN_MAX_PARALLEL',
      },
    ],
    active_jobs: [],
    recent_jobs: [],
  }
}

/** The turn output the artboard shows, as the log endpoint would deliver it. */
export const EXAMPLE_LOG = [
  { time: '14:51:16', kind: 'turn', message: 'Turn 1 started on mini-2' },
  { time: '14:51:17', kind: 'session', message: 'Cursor session connected' },
  { time: '14:51:18', kind: 'read', message: 'Reading workspace and project configuration' },
  { time: '14:51:21', kind: 'inspect', message: 'Inspecting project files' },
  { time: '14:51:28', kind: 'run', message: 'Running smoke check' },
  { time: '14:51:36', kind: 'stream', message: 'Waiting for next output…' },
]
